[package]
name = "mini-retry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "2.0.0"
futures-core = "0.3.26"
pin-project = "1"
tokio = { version = "1", features = ["time"] }